In [12]:
# Importing the Libraries:
import pandas as pd
import matplotlib.pyplot as plt

# Loading the Dataset:
df_olympics = pd.read_csv("olympics_08_medalists.csv")
df_olympics.head()

# Inspecting the Data:
df_olympics.info()
df_olympics.columns

# Printing the Original Untidy Dataset:
print("Original (Untidy) Olympics DataFrame:")
print(df_olympics.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1875 entries, 0 to 1874
Data columns (total 71 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   medalist_name                 1875 non-null   object
 1   male_archery                  11 non-null     object
 2   female_archery                9 non-null      object
 3   male_athletics                85 non-null     object
 4   female_athletics              81 non-null     object
 5   male_badminton                12 non-null     object
 6   female_badminton              10 non-null     object
 7   male_baseball                 72 non-null     object
 8   male_basketball               35 non-null     object
 9   female_basketball             36 non-null     object
 10  male_boxing                   44 non-null     object
 11  male_canoeing and kayaking    53 non-null     object
 12  female_canoeing and kayaking  21 non-null     object
 13  male_road bicycle racing      5 non-null      object
 14  female_road bicycle racing    6 non-null      object
 15  male_track cycling            35 non-null     object
 16  female_track cycling          9 non-null      object
 17  male_mountain biking          3 non-null      object
 18  female_mountain biking        3 non-null      object
 19  male_bmx                      3 non-null      object
 20  female_bmx                    3 non-null      object
 21  male_diving                   16 non-null     object
 22  female_diving                 13 non-null     object
 23  female_equestrian sport       20 non-null     object
 24  male_equestrian sport         18 non-null     object
 25  male_fencing                  28 non-null     object
 26  female_fencing                26 non-null     object
 27  male_field hockey             50 non-null     object
 28  female_field hockey           48 non-null     object
 29  male_association football     55 non-null     object
 30  female_association football   54 non-null     object
 31  male_artistic gymnastics      29 non-null     object
 32  female_artistic gymnastics    20 non-null     object
 33  female_rhythmic gymnastics    21 non-null     object
 34  male_trampoline gymnastics    3 non-null      object
 35  female_trampoline gymnastics  3 non-null      object
 36  male_handball                 43 non-null     object
 37  female_handball               42 non-null     object
 38  male_judo                     28 non-null     object
 39  female_judo                   28 non-null     object
 40  male_modern pentathlon        3 non-null      object
 41  female_modern pentathlon      2 non-null      object
 42  male_rowing                   83 non-null     object
 43  female_rowing                 58 non-null     object
 44  male_sailing                  33 non-null     object
 45  female_sailing                21 non-null     object
 46  male_shooting sport           26 non-null     object
 47  female_shooting sport         17 non-null     object
 48  female_softball               45 non-null     object
 49  male_swimming                 62 non-null     object
 50  female_swimming               63 non-null     object
 51  female_synchronized swimming  29 non-null     object
 52  male_table tennis             9 non-null      object
 53  female_table tennis           9 non-null      object
 54  male_taekwondo                16 non-null     object
 55  female_taekwondo              16 non-null     object
 56  male_tennis                   9 non-null      object
 57  female_tennis                 9 non-null      object
 58  male_triathlon                3 non-null      object
 59  female_triathlon              3 non-null      object
 60  male_beach volleyball         6 non-null      object
 61  female_beach volleyball       6 non-null      object
 62  male_volleyball               36 non-null     object
 63  female_volleyball             36 non-null     object
 64  male_water polo               39 non-null     object
 65  female_water polo             39 non-null     object
 66  male_weightlifting            24 non-null     object
 67  female_weightlifting          21 non-null     object
 68  male_freestyle wrestling      28 non-null     object
 69  female_freestyle wrestling    16 non-null     object
 70  male_greco-roman wrestling    27 non-null     object
dtypes: object(71)
memory usage: 1.0+ MB
Original (Untidy) Olympics DataFrame:
       medalist_name male_archery female_archery male_athletics  \
0    Aaron Armstrong          NaN            NaN           gold
1      Aaron Peirsol          NaN            NaN            NaN
2   Abdullo Tangriev          NaN            NaN            NaN
3  Abeer Abdelrahman          NaN            NaN            NaN
4            Abhinav          NaN            NaN            NaN

  female_athletics male_badminton female_badminton male_baseball  \
0              NaN            NaN              NaN           NaN
1              NaN            NaN              NaN           NaN
2              NaN            NaN              NaN           NaN
3              NaN            NaN              NaN           NaN
4              NaN            NaN              NaN           NaN

  male_basketball female_basketball  ... female_beach volleyball  \
0             NaN               NaN  ...                     NaN
1             NaN               NaN  ...                     NaN
2             NaN               NaN  ...                     NaN
3             NaN               NaN  ...                     NaN
4             NaN               NaN  ...                     NaN

  male_volleyball female_volleyball male_water polo female_water polo  \
0             NaN               NaN             NaN               NaN
1             NaN               NaN             NaN               NaN
2             NaN               NaN             NaN               NaN
3             NaN               NaN             NaN               NaN
4             NaN               NaN             NaN               NaN

  male_weightlifting female_weightlifting male_freestyle wrestling  \
0                NaN                  NaN                      NaN
1                NaN                  NaN                      NaN
2                NaN                  NaN                      NaN
3                NaN               bronze                      NaN
4                NaN                  NaN                      NaN

  female_freestyle wrestling male_greco-roman wrestling
0                        NaN                        NaN
1                        NaN                        NaN
2                        NaN                        NaN
3                        NaN                        NaN
4                        NaN                        NaN

[5 rows x 71 columns]

In [13]:
# Cleaning the Data using melt. 
# Converting medal columns into one column called "Medal_Info"
# and their values into "Count".
df_olympics_melted = pd.melt(
    df_olympics,
    id_vars = ["medalist_name"],
    var_name = "Medal_Info",
    value_name = "Count")

print("\nMelted (Partially Tidy) Olympics DataFrame:")
print(df_olympics_melted.head())

Melted (Partially Tidy) Olympics DataFrame:
       medalist_name    Medal_Info Count
0    Aaron Armstrong  male_archery   NaN
1      Aaron Peirsol  male_archery   NaN
2   Abdullo Tangriev  male_archery   NaN
3  Abeer Abdelrahman  male_archery   NaN
4            Abhinav  male_archery   NaN

In [14]:
# Splitting the columns using "str.split()":
# Splitting "Medal_Info" into two columns:
df_olympics_melted[["Medal", "Category"]] = df_olympics_melted["Medal_Info"].str.split('_', expand = True)

print("\nAfter Splitting Columns:")
print(df_olympics_melted.head())

After Splitting Columns:
       medalist_name    Medal_Info Count Medal Category
0    Aaron Armstrong  male_archery   NaN  male  archery
1      Aaron Peirsol  male_archery   NaN  male  archery
2   Abdullo Tangriev  male_archery   NaN  male  archery
3  Abeer Abdelrahman  male_archery   NaN  male  archery
4            Abhinav  male_archery   NaN  male  archery

In [34]:
# Final Tidy DataFrame:
tidy_olympics = df_olympics_melted[["medalist_name", "Medal", "Category", "Count"]]

print("\nFinal (Tidy) Olympics DataFrame:")
print(tidy_olympics.head())

Final (Tidy) Olympics DataFrame:
       medalist_name Medal Category Count
0    Aaron Armstrong  male  archery   NaN
1      Aaron Peirsol  male  archery   NaN
2   Abdullo Tangriev  male  archery   NaN
3  Abeer Abdelrahman  male  archery   NaN
4            Abhinav  male  archery   NaN

In [35]:
tidy_olympics

            medalist_name Medal               Category Count
0         Aaron Armstrong  male                archery   NaN
1           Aaron Peirsol  male                archery   NaN
2        Abdullo Tangriev  male                archery   NaN
3       Abeer Abdelrahman  male                archery   NaN
4                 Abhinav  male                archery   NaN
...                   ...   ...                    ...   ...
131245        Éver Banega  male  greco-roman wrestling   NaN
131246  Ólafur Stefánsson  male  greco-roman wrestling   NaN
131247      Óscar Brayson  male  greco-roman wrestling   NaN
131248   Łukasz Pawłowski  male  greco-roman wrestling   NaN
131249        Živko Gocić  male  greco-roman wrestling   NaN

[131250 rows x 4 columns]

In [36]:
tidy_olympics.dropna(inplace = True)

C:\Users\lawso\AppData\Local\Temp\ipykernel_25152\821239295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tidy_olympics.dropna(inplace = True)

In [37]:
# Visualization 1 - Total Medals by country:
#tidy_olympics['Count'] = pd.to_numeric(tidy_olympics['Count'], errors='coerce')
#tidy_olympics = tidy_olympics.dropna(subset=['Count'])

# Inspecting data before dropping anything:
print(tidy_olympics.head(10))
print(tidy_olympics['Count'].unique())

# Cleaning the count column properly:
#tidy_olympics['Count'] = tidy_olympics['Count'].astype(str)

#tidy_olympics['Count'] = tidy_olympics['Count'].str.replace(',', '')
#tidy_olympics['Count'] = tidy_olympics['Count'].str.replace(' ', '')

# Converting values to numeric values:
#tidy_olympics['Count'] = pd.to_numeric(tidy_olympics['Count'], errors='coerce')

# Drop Missing Values:
print(tidy_olympics['Count'].isna().sum())
print(len(tidy_olympics))

#tidy_olympics = tidy_olympics.dropna(subset=['Count'])

# Plotting the values:
medalist_name_totals = tidy_olympics.groupby('medalist_name')['Count'].sum()
tidy_olympics
#medalist_name_totals.head(10).plot(kind='bar')
#plt.show()

#medalist_name_totals = tidy_olympics.groupby('medalist_name')['Count'].sum().sort_values(ascending=False)

#medalist_name_totals.head(10).plot(kind='bar')
#plt.title("Top 10 Countries by Total Medals (2008)")
#plt.ylabel("Number of Medals")
#plt.xlabel("Country")
#plt.show()

#print(df_olympics.columns)
#print(df_olympics.head())

       medalist_name Medal Category   Count
177     Bair Badënov  male  archery  bronze
676    Ilario Di Buò  male  archery  silver
682     Im Dong-hyun  male  archery    gold
760        Jiang Lin  male  archery  bronze
920   Lee Chang-hwan  male  archery    gold
950       Li Wenquan  male  archery  bronze
1043  Marco Galiazzo  male  archery  silver
1107   Mauro Nespoli  male  archery  silver
1314   Park Kyung-mo  male  archery  silver
1710    Viktor Ruban  male  archery    gold
['bronze' 'silver' 'gold']
0
1875

              medalist_name Medal               Category   Count
177            Bair Badënov  male                archery  bronze
676           Ilario Di Buò  male                archery  silver
682            Im Dong-hyun  male                archery    gold
760               Jiang Lin  male                archery  bronze
920          Lee Chang-hwan  male                archery    gold
...                     ...   ...                    ...     ...
130932        Steeve Guénot  male  greco-roman wrestling    gold
131159  Yannick Szczepaniak  male  greco-roman wrestling  bronze
131162       Yavor Yanakiev  male  greco-roman wrestling  bronze
131200      Yury Patrikeyev  male  greco-roman wrestling  bronze
131234         Zoltán Fodor  male  greco-roman wrestling  silver

[1875 rows x 4 columns]

In [46]:
# Visualization 2 - Medal Distrubutor:
medal_counts = tidy_olympics[["Medal", "Count"]].groupby(by = ['Medal']).agg(['count'])

print(medal_counts) 

#medal_counts = medal_counts[medal_counts > 0]  # remove zeros

medal_counts.plot(kind='pie', autopct='%1.1f%%')
plt.title("Medal Distribution")
plt.ylabel("")
plt.show()

print(tidy_olympics.head())
print(tidy_olympics.columns)

       Count
       count
Medal
female   843
male    1032

ValueError: pie requires either y column or 'subplots=True'

In [18]:
# Pivot Table:
# Summarizes medal counts by type
# Demonstrates aggregation on tidy data

pivot = pd.pivot_table(
    tidy_olympics,
    values='Count',
    index='medalist_name',
    columns='Medal',
    aggfunc='sum'
)

pivot.head()

Empty DataFrame
Columns: []
Index: []