In [1]:
# Import neccesary libraries:
import pandas as pd
import numpy as np

# Download Data:
from sklearn.datasets import fetch_california_housing

# Load the Housing Data Set:
housing = fetch_california_housing()

# Creating a Pandas DataFrame for the features and a series for the target variable:
x = pd.DataFrame(housing.data, columns=housing.feature_names)
y = pd.Series(housing.target, name='med_house_value')

# Displaying the first five rows:
print("First 5 rows of data:")
x.head()

First 5 rows of data:

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [2]:
# Printing the Feature Names and Checking for missing values:
print("Feature Names:")
print(housing.feature_names)
print("\nMissing Values:")
print(x.isnull().sum())

Feature Names:
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

Missing Values:
MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [3]:
# Summary Statistics:
x.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [4]:
# Splitting the data set into training and test sets:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Training a linear regression model on unscaled data:
model = LinearRegression()
model.fit(x_train, y_train)

# Making predictions on the test set:
y_pred = model.predict(x_test)

In [5]:
# Evaluating model performance using MSE, RMSE, and R^2:
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)

r2 = r2_score(y_test, y_pred)

print("Unscaled Data Model:")
print(f"Mean Squared Error: {mse:.2f}")
print(f"Root Squared Error: {rmse:.2f}")
print(f"R² Score: {r2:.2f}")

Unscaled Data Model:
Mean Squared Error: 0.56
Root Squared Error: 0.75
R² Score: 0.58

In [6]:
# 8: The R squared score inicates the proportion of the variance in the target variable explained by the model.
# An R squared score close to 1 suggests that there is a very good fit, while an R squared score close to 0 
# indicates that the model failed to capture much variance. My R squared score of 0.58 means the model roughly
# explains 58% of the variation in housing prices. My model captures important iformation but definently leaves
# room for improvement. In class we learned that it is often misleading to compare features as they have different 
# units. In my model, I think that MedInc has the strongest impact as it has the largest possible coefficient. 
# I also noticed that Latitude and and Longitude have strong effects and that higher income usually correlates with
# higher house value. Certain geographical locations also significantly influence the price. The RMSE tells me that 
# the predictions are off by about 0.75 (in units of $100,000). This means that the average prediction error is about
# $75,000.

In [7]:
# Selecting Three Features:
selected_features = ["MedInc", "AveRooms", "Latitude"]
x_selected = x[selected_features]

# I selected MenInc, AveRooms, and Latitude because median income strongly influences affordability, average rooms
# reflect house size, and Latitude explains the price changes in different locations.

# Training a new linear regression model:
x_train_s, x_test_s, y_train_s, y_test_s = train_test_split(x_selected, y, test_size=0.2, random_state=42)

simple_model = LinearRegression()
simple_model.fit(x_train_s, y_train_s)

y_pred_s = simple_model.predict(x_test_s)

# Evaluating the performance of the simplified model:
mse_s = mean_squared_error(y_test_s, y_pred_s)
rmse_s = np.sqrt(mse_s)
r2_s = r2_score(y_test_s, y_pred_s)

mse_s, rmse_s, r2_s

print("Simplified Data Model:")
print(f"Mean Squared Error: {mse_s:.2f}")
print(f"Root Squared Error: {rmse_s:.2f}")
print(f"R² Score: {r2_s:.2f}")

# So in this model, the RMSE is slightly lower than the R squared score in the first model.

# 16: The simplified model performs slightly worse than the full model. The full model has an R squared score of 0.58
# which means the model roughly explains 58% of the variation. The simplified model has a R squared score of 0.47 which 
# means the model roughly explains only 47% of the variation. The full model captures more information and produces better 
# predictions while the simplified model is easier to interpret and build but is less accurate. The specific situation would dictate which 
# model I would prefer to use. For example, if accuracy was the most important factor, I would choose to use the full model 
# rather than the simplified model.

Simplified Data Model:
Mean Squared Error: 0.69
Root Squared Error: 0.83
R² Score: 0.47